services:
  redis-master-1:
    container_name: redis-master-1
    image: redis:latest
    command: ["redis-server", "--port", "6379", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    restart: always
    ports:
      - 6379:6379
      - 6479:6479
      - 6579:6579
      - 6380:6380
      - 6480:6480
      - 6580:6580

  redis-master-2:
    network_mode: "service:redis-master-1"
    container_name: redis-master-2
    image: redis:latest
    command: ["redis-server", "--port", "6479", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    restart: always

  redis-master-3:
    network_mode: "service:redis-master-1"
    container_name: redis-master-3
    image: redis:latest
    command: ["redis-server", "--port", "6579", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    restart: always

  redis-slave-1:
    network_mode: "service:redis-master-1"
    container_name: redis-slave-1
    image: redis:latest
    command: ["redis-server", "--port", "6380", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    restart: always

  redis-slave-2:
    network_mode: "service:redis-master-1"
    container_name: redis-slave-2
    image: redis:latest
    command: ["redis-server", "--port", "6480", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    restart: always

  redis-slave-3:
    network_mode: "service:redis-master-1"
    container_name: redis-slave-3
    image: redis:latest
    command: ["redis-server", "--port", "6580", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    restart: always

  redis_cluster_entry:
    network_mode: "service:redis-master-1"
    image: redis:latest
    container_name: redis_cluster_entry
    command: redis-cli --cluster create 127.0.0.1:6379 127.0.0.1:6479 127.0.0.1:6579 127.0.0.1:6380 127.0.0.1:6480 127.0.0.1:6580 --cluster-yes
    depends_on:
      - redis-master-1
      - redis-master-2
      - redis-master-3
      - redis-slave-1
      - redis-slave-2
      - redis-slave-3
