services:
  redis-master-1:
    network_mode: "host"
    container_name: redis-master-1
    image: redis:latest
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - redis-master-1-data:/data

  redis-master-2:
    network_mode: "host"
    container_name: redis-master-2
    image: redis:latest
    command: redis-server --port 6479 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - redis-master-2-data:/data

  redis-master-3:
    network_mode: "host"
    container_name: redis-master-3
    image: redis:latest
    command: redis-server --port 6579 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - redis-master-3-data:/data

  redis-slave-1:
    network_mode: "host"
    container_name: redis-slave-1
    image: redis:latest
    command: redis-server --port 6380 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - redis-slave-1-data:/data

  redis-slave-2:
    network_mode: "host"
    container_name: redis-slave-2
    image: redis:latest
    command: redis-server --port 6480 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - redis-slave-2-data:/data

  redis-slave-3:
    network_mode: "host"
    container_name: redis-slave-3
    image: redis:latest
    command: redis-server --port 6580 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    volumes:
      - redis-slave-3-data:/data

  redis_cluster_entry:
    network_mode: "host"
    image: redis:latest
    container_name: redis_cluster_entry
    command: >
      bash -c "
        sleep 10 &&
        redis-cli --cluster create {serverIPAddress}:6379 {serverIPAddress}:6479 {serverIPAddress}:6579 {serverIPAddress}:6380 {serverIPAddress}:6480 {serverIPAddress}:6580 --cluster-replicas 1 --cluster-yes
      "
    depends_on:
      - redis-master-1
      - redis-master-2
      - redis-master-3
      - redis-slave-1
      - redis-slave-2
      - redis-slave-3

volumes:
  redis-master-1-data:
  redis-master-2-data:
  redis-master-3-data:
  redis-slave-1-data:
  redis-slave-2-data:
  redis-slave-3-data:
